<a href="https://colab.research.google.com/github/rainforest01-coder/ESAA_files/blob/main/ESAA_YB_WEEK1_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: 

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(array1.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array2=np.zeros(10)
array2[4]=1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
array6=np.arange(10,50)

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
array6_reversed=array6[::-1]
print(array6_reversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array8=np.arange(0,9).reshape(3,3)
print(array8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array=np.array([1,2,0,0,4,0])
print(np.nonzero(array))

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [14]:
identity_array=np.identity(3)
identity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [15]:
array=np.random.random((3,3,3))
print(array)

[[[0.8190669  0.65991357 0.87338131]
  [0.1827893  0.51968192 0.18942664]
  [0.94510927 0.40949595 0.60516852]]

 [[0.59478753 0.91500733 0.61285043]
  [0.89166731 0.46290153 0.19408099]
  [0.79244974 0.63034314 0.61460282]]

 [[0.49647668 0.10080844 0.78027935]
  [0.40949214 0.52195452 0.49133291]
  [0.3503069  0.80280784 0.99567165]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [16]:
array=np.random.random((10,10))
print(array)
print(np.min(array))
print(np.max(array))

[[0.85515874 0.78546283 0.21028571 0.1051572  0.04292441 0.42855952
  0.82057956 0.09759731 0.280747   0.67012752]
 [0.60115071 0.31062528 0.09642783 0.87891535 0.95038752 0.22921901
  0.83802226 0.42279294 0.18121414 0.52154374]
 [0.36862534 0.07104724 0.38890642 0.80685067 0.75484351 0.21116086
  0.38204863 0.78710916 0.94931108 0.43667794]
 [0.13186483 0.66051716 0.644098   0.40259064 0.26293793 0.68424613
  0.49036794 0.35877123 0.77514673 0.27831571]
 [0.07798651 0.90088792 0.66929154 0.60276174 0.44859518 0.73962375
  0.693787   0.22635821 0.90444539 0.57031692]
 [0.2939315  0.13480123 0.9355093  0.76071668 0.82806864 0.43452559
  0.95115524 0.59332896 0.16780873 0.7142307 ]
 [0.50877081 0.98079437 0.87801796 0.95543252 0.98941918 0.79493213
  0.93911313 0.0839453  0.48940579 0.22950079]
 [0.86949623 0.84360013 0.04554031 0.39237983 0.15278964 0.71571886
  0.72083009 0.98767378 0.39163484 0.89164125]
 [0.46793485 0.18870358 0.53320222 0.54960256 0.34239575 0.23596197
  0.01506039

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [17]:
array=np.random.random(30)
print(array)
print(np.mean(array))

[0.58462381 0.13501578 0.43184431 0.24013218 0.18958675 0.36025349
 0.1224     0.79253106 0.98716259 0.77333757 0.81619166 0.02721391
 0.11253156 0.95539095 0.40547218 0.08747195 0.37894633 0.76602716
 0.83431677 0.45693531 0.36179072 0.62158969 0.08792416 0.45416836
 0.32915458 0.63161053 0.59988001 0.39178895 0.32483497 0.33683884]
0.4532322039633415


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [18]:
array=np.ones((5,5))
array[1:-1,1:-1]=0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```



```
# 코드로 형식 지정됨
```

nan False False nan True False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [19]:
array=np.zeros((5,5))
array[[1,2,3,4],[0,1,2,3]]=[1,2,3,4]
print(array)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
array=np.zeros((8,8))
array[1::2, 0::2] = 1
array[0::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [23]:
coord=np.unravel_index(100, (6,7,8))
coord = tuple(map(int, coord))
print(coord)

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [24]:
array=np.random.random((5,5))
mean=np.mean(array)
std=np.std(array)
array=(array-mean)/std
print(array)

[[ 1.33366778 -1.22791586  1.27699564 -1.49013344  1.31379024]
 [ 0.14259511 -0.87031237  0.26917976 -1.54974954  1.30147656]
 [ 0.13323749  0.05967563 -1.42721727 -0.26693787 -0.10730761]
 [ 0.8928939   0.25321248 -0.1785352   1.12455115 -1.21048965]
 [ 0.7431251  -0.75844281  0.54105405 -1.55661083  1.25819756]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [25]:
color_dtype = np.dtype([
    ('R', np.ubyte),
    ('G', np.ubyte),
    ('B', np.ubyte),
    ('A', np.ubyte)
])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
array1=np.random.random((5,3))
array2=np.random.random((3,2))
result=np.dot(array1,array2)
print(result)

[[0.7184353  0.64039242]
 [0.47073551 0.42770007]
 [1.21712748 0.61831469]
 [1.20713294 0.81183883]
 [0.84997873 0.60322377]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [27]:
array=np.array([1,3,5,7,9])
array[(array>3) & (array<8)]*=-1
print(array)

[ 1  3 -5 -7  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [ ]:
#Z<Z>Z 제외 ,legal

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
#/tmp/ipython-input-1119427974.py:1: RuntimeWarning: invalid value encountered in dividenp.array(0) / np.array(0)
#/tmp/ipython-input-1119427974.py:2: RuntimeWarning: divide by zero encountered in floor_dividenp.array(0) // np.array(0)
#/tmp/ipython-input-1119427974.py:3: RuntimeWarning: invalid value encountered in castnp.array([np.nan]).astype(int).astype(float)
#array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [29]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common = np.intersect1d(Z1, Z2)
print("Common values:", common)

Common values: [2 4 5 6 7 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [30]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
result = np.empty_like(A)
tmp = np.empty_like(A)
np.add(A, B, out=tmp)
np.divide(A, 2, out=result)
np.negative(result, out=result)
np.multiply(tmp, result, out=result)

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [37]:
array=np.random.uniform(0,10,10)
print(array)
array1=array-(array%1)
print(array1)
print(array//1)

[8.66371876 0.32348272 1.05162769 7.90694681 0.25863571 6.49634791
 5.00848666 5.79665611 3.94690428 5.81133846]
[8. 0. 1. 7. 0. 6. 5. 5. 3. 5.]
[8. 0. 1. 7. 0. 6. 5. 5. 3. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
array=np.zeros((5,5))
array+=np.arange(5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [39]:
array=np.random.random(10)
array.sort()
print(array)

[0.0736842  0.55963274 0.58232666 0.62312649 0.6476664  0.8242285
 0.92959334 0.94727307 0.97048339 0.9773648 ]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [40]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [41]:
cartesian = np.random.rand(10, 2)
print("Cartesian coordinates:\n", cartesian)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)         # 거리
theta = np.arctan2(y, x)         # 각도 (라디안)

polar = np.column_stack((r, theta))
print("\nPolar coordinates (r, theta):\n", polar)

Cartesian coordinates:
 [[0.70787718 0.69630648]
 [0.39828009 0.33112133]
 [0.34783234 0.1261323 ]
 [0.44482612 0.51692741]
 [0.99192433 0.15225507]
 [0.35633974 0.66009492]
 [0.36310903 0.5127752 ]
 [0.69862416 0.40702164]
 [0.56482533 0.26540493]
 [0.95354727 0.65773104]]

Polar coordinates (r, theta):
 [[0.9929415  0.77715819]
 [0.51794629 0.69358323]
 [0.36999553 0.34787644]
 [0.68197084 0.86022675]
 [1.00354147 0.15230593]
 [0.75013553 1.07579388]
 [0.62832044 0.95463802]
 [0.80854334 0.52753055]
 [0.62407325 0.43926956]
 [1.1583879  0.60382909]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [42]:
array=np.random.random(10)
print(array)
array[array.argmax()]=0
print(array)

[0.12284415 0.92615237 0.19418167 0.82273999 0.76249229 0.49564911
 0.53066689 0.45578833 0.75379764 0.49955525]
[0.12284415 0.         0.19418167 0.82273999 0.76249229 0.49564911
 0.53066689 0.45578833 0.75379764 0.49955525]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [43]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distances=np.abs(Z-v)
closest_index=distances.argmin()
print(Z[closest_index])

96


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [44]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [45]:
n = 5
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),7)
print(Z)

[[0. 0. 0. 0. 7.]
 [7. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 7.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [47]:
# column 3
Z = np.random.randint(0,10,(3,3))
n = 2
sorted_indices = Z[:, n].argsort()
Z_sorted = Z[sorted_indices]
print("\nArray sorted by column", n, ":\n", Z_sorted)


Array sorted by column 2 :
 [[1 8 0]
 [2 2 3]
 [2 6 9]]


In [48]:
# column 2
Z = np.random.randint(0,10,(3,3))
n = 1
sorted_indices = Z[:, n].argsort()
Z_sorted = Z[sorted_indices]
print("\nArray sorted by column", n, ":\n", Z_sorted)


Array sorted by column 1 :
 [[2 0 2]
 [6 6 6]
 [2 9 1]]
