<a href="https://colab.research.google.com/github/rainforest01-coder/ESAA_files/blob/main/esaa_week01_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#01 머신러닝의 개념  

데이터를 기반으로 통계적인 신뢰도를 강화하고 예측오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출



###머신러닝의 분류

1. 지도학습: 분류, 회귀, 시각 음성 감지, 텍스트 분석 등등
2. 비지도 학습: 클러스터링, 차원 축소, 강화학습
3. 강화학습



###데이터 전쟁

최적의 머신러닝 알고리즘과 모델 파라미터를 구축하는 능력도 중요하지만 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 더 중요



#02파이썬 머신러닝 생태계를 구성하는 주요 패키지

-머신러닝 패키지: 사이킷런  
-행렬/선형대수/통계 패키지: 넘파이  
-시각화: 맷플롯립, 시본(단순화)  

#03넘파이

###넘파이 ndarray 개요
```
import numpy as np
array1=np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태',array1.shape)

array2=np.array([[1,2,3],[4,5,6]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3=np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태',array3.shape)

print('array1:{0}차원, array2:{1}차원, array3:{2}차원'.format(array1.ndim,array2.ndim,array3.ndim))
```

[output]  
array1 type: <class 'numpy.ndarray'>  
array1 array 형태 (3,)  
array2 type: <class 'numpy.ndarray'>  
array2 array 형태: (2, 3)  
array3 type: <class 'numpy.ndarray'>  
array3 array 형태 (1, 3)   
**array1:1차원, array2:2차원, array3:2차원**

*차원이 다르면 오류 발생하므로 주의*

###ndarray의 데이터 타입

한 개의 ndarray 객체에 int와 float 함께 있을 수 없음

```
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)
```
[output]  
<class 'list'>  
<class 'numpy.ndarray'>  
[1 2 3] int64  

```
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)
```

[output]  
['1' '2' 'test'] <U21  
[1. 2. 3.] float64  
서로 다른 데이터 타입이 있을 경우 큰 데이터 타입으로 변환

```
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)
```
[output]  
[1. 2. 3.] float64  
[1 2 3] int32  
[1 2 3] int32  

###ndarray를 편리하게 생성하기-arange, zeros, ones

1. arange()
```
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
```
[output]  
[0 1 2 3 4 5 6 7 8 9]  0부터 함수 인자값의 -1까지 순차적으로  
int64 (10,)


2. zeros()
함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray로 반환


3. ones()
위와 유사, 함수 인자로 dtype 지정 안할 시 float64

```
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)
````
[output]  
[[0 0]  
 [0 0]  
 [0 0]]  
int32 (3, 2)  
[[1. 1.]  
 [1. 1.]  
 [1. 1.]]  
float64 (3, 2)  


###ndarray의 차원과 크기를 변경하는 reshape()

```
array1=np.arange(10)
print('array1:\n',array1)
array2=array1.reshape(2,5)
print('array2:\n',array2)
array3=array1.reshape(5,2)
print('array3:\n',array3)
```
[output]  
array1:  
 [0 1 2 3 4 5 6 7 8 9]  
array2:  
 [[0 1 2 3 4]  
 [5 6 7 8 9]]  
array3:  
 [[0 1]  
 [2 3]  
 [4 5]  
 [6 7]  
 [8 9]]  

 *지정된 사이즈로 변경 불가시 오류*

 -인자에 -1을 적용하면 원래으 ndarray에 호환되는 새로운 shape으로 변환
 ```
 array1=np.arange(10)
 print(array1)
 array2=array1.reshape(-1,5)
 print('array2 shape:', array2.shape)
 ```
 [output]
 [0 1 2 3 4 5 6 7 8 9]  
array2 shape: (2, 5)

-reshape(-1,1)
원본 ndarray가 어떤 형태라도 2차원이고 1개의 칼럼을 가진 ndarray로 변환됨

```
array1=np.arange(8)
array3d=array1.reshape(2,2,2)
print('array3d:\n',array3d.tolist())

array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:', array5.shape)

array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:\n', array6.shape)
```
[output]  
array3d:  
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]  
array5:  
 [[0], [1], [2], [3], [4], [5], [6], [7]]  
array5 shape: (8, 1)  
array6:  
 [[0], [1], [2], [3], [4], [5], [6], [7]]  
array6 shape: (8, 1)  

###넘파이의 ndarray의 데이터 세트 선택하기-인덱싱

1. 단일 값 추출 array[index값]
-1은 맨 뒤에서 첫번째 인덱스
```
array1=np.arange(1,10)
value=array1[2]
print(value)
print(type(value))
```
[output]
3  
<class 'numpy.int64'>  

-단일 인덱스 이용해 ndarray 내 데이터값 간단히 수정
```
array1[0]=9
array1[8]=0
print(array1)
```
[output]  
[9 2 3 4 5 6 7 8 0]


-다차원 ndarray에서 단일 값 추출
```
array2d=np.arange(1,10).reshape(3,3)
print(array2d)
print(array2d[0,0])
print(array2d[3,3])
```
[output]  
[[1 2 3]  
 [4 5 6]  
 [7 8 9]]  
1  
9  
**axis0: 로우(행), axis1: 칼럼(열)**

2. 슬라이싱 array[start:stop]
**1차원**
ndarray타입
```
array1=np.arange(1,10)
array3=array1[0:3]
print(array3, type(array3))
```
[output]
[1 2 3] <class 'numpy.ndarray'>

-시작인덱스 생략시 처음 인덱스부터, 종료 인덱스 생략시 마지막 인덱스까지

**2차원**
```
array2d=np.arange(1,10).reshape(3,3)
print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:,0]\n',array2d[:,0])
print('array2d[0]\n',array2d[0])
```
-output  
array2d[0:2,0:2]  
 [[1 2]  
 [4 5]]  
array2d[1:3,0:3]  
 [[4 5 6]  
 [7 8 9]]  
array2d[:,:]  
 [[1 2 3]  
 [4 5 6]  
 [7 8 9]]  
 array2d[:,0]   
 [1 4 7]    
 array2d[0] *2차원에서 뒤에 오는 인덱스 없애면 1차원 ndarray반환*  
 [1 2 3]  

 3. 팬시 인덱싱
 리스트나 ndarray로 인덱스 집합을 지정하여 해당 인덱스의 ndarray 반환
 ```
 array2d=np.arange(1,10).reshape(3,3)
 array3=array2d[[0,1],2]
 print('array3:',array3)
 array4=array2d[[0,1],0:2]
 print('array4:',array4)
 array5=array2d[[0,1]]
 print('array5:\n',array5)
 ```
 -output  
 array3: [3 6]  
array4:  
 [[1 2]  
 [4 5]]  
 array5:  
 [[1 2 3]  
 [4 5 6]]  


 4. 불린 인덱싱 array[조건문]

```
array1d=np.arange(1,10)
array3=array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:',array3)
```
-output
array1d>5 불린 인덱싱 결과 값: [6 7 8 9]

```
array1d>5
```
-output  
array([False, False, False, False, False,  True,  True,  True,  True])  
*true인 인덱스만 반환되어 해당 인덱스 ndarray 조회*


###행렬의 정렬

1. sort()  
-np.sort(ndarray): 원 행렬 그대로 유지  
-ndarray.sort(): 원 행렬 자체를 정렬, 반환값은 None
```
org_array=np.array([3,1,9,5])
print('원본행렬:',org_array)

sort_array1=np.sort(org_array)
print('np.sort()후 반환된 행렬:',sort_array1)
print('np.sort()후 원본 행렬:',org_array)

sort_array2=org_array.sort()
print('org_array.sort()후 반환된 행렬:',sort_array2)
print('org_array.sort()후 원본 행렬:',org_array)
```
-output  
원본행렬: [3 1 9 5]  
np.sort()후 반환된 행렬: [1 3 5 9]  
np.sort()후 원본 행렬: [3 1 9 5]  
**org_array.sort()후 반환된 행렬: None**  
org_array.sort()후 원본 행렬: [1 3 5 9]  



-내림차순으로 정렬[::-1] 붙이기
```
org_array=np.array([3,1,9,5])
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)
```
-output
내림차순으로 정렬: [9 5 3 1]

-행렬이 2차원 이상일 경우: axis 축 값을 설정
```
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d, axis=0)
print('로우 방향 정렬:',sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d, axis=1)
print('칼럼 방향 정렬:',sort_array2d_axis1)
```

-output  
로우 방향 정렬: [[ 7  1]
 [ 8 12]]
칼럼 방향 정렬: [[ 8 12]
 [ 1  7]]

 -np.argsort(): 정렬된 행렬의 인덱스 반환

 ```
 org_array=np.array([3,1,9,5])
 sort_indices=np.argsort(org_array)
 print(type(sort_indices))
 print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)
 ```
 -output  
 <class 'numpy.ndarray'> 원본 행렬의 인덱스를 ndarray형으로 반환  
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]  
*내림차순은 뒤에 [::-1]붙이기*

**활용**
```
name_array=np.array(['A','B','C','D','E'])
score_array=np.array([78,95,84,98,88])
sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:',name_array[sort_indices_asc])
```
-output  
성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]  
성적 오름차순으로 name_array의 이름 출력: ['A' 'C' 'E' 'B' 'D']  


###선형대수 연산


1. 행렬 내적: np.dot()
```
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print(dot_product)
```
-output  
[[ 58  64]  
 [139 154]]  

 2. 전치 행렬: np.transpose()
 ```
 A=np.array([[1,2],[3,4]])
 transpose_mat=np.transpose(A)
 print(transpose_mat)
 ```
 -output  
 [[1 3]  
 [2 4]]  
