<a href="https://colab.research.google.com/github/rainforest01-coder/ESAA_files/blob/main/YB_0905_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
array1=np.random.random((5,3))
array2=np.random.random((3,2))
result=np.dot(array1,array2)
print(result)

[[0.7184353  0.64039242]
 [0.47073551 0.42770007]
 [1.21712748 0.61831469]
 [1.20713294 0.81183883]
 [0.84997873 0.60322377]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
array=np.array([1,3,5,7,9])
array[(array>3) & (array<8)]*=-1
print(array)

[ 1  3 -5 -7  9]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

*   Python Built-in sum Function: The sum of range(5) (which is 0 + 1 + 2 + 3 + 4 = 10) is computed, and then -1 is added to it. The result will be 9
*   NumPy's sum Function: NumPy's sum function doesn't treat the second argument as a start value like Python's built-in sum. Instead, it treats it as an axis parameter. Since -1 is not a valid axis for a 1D sequence (the valid axis for a 1D array is 0), NumPy will raise a TypeError


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```


In [ ]:
#Z<Z>Z 제외 ,legal

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
#/tmp/ipython-input-1119427974.py:1: RuntimeWarning: invalid value encountered in dividenp.array(0) / np.array(0)
#/tmp/ipython-input-1119427974.py:2: RuntimeWarning: divide by zero encountered in floor_dividenp.array(0) // np.array(0)
#/tmp/ipython-input-1119427974.py:3: RuntimeWarning: invalid value encountered in castnp.array([np.nan]).astype(int).astype(float)
#array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
common = np.intersect1d(Z1, Z2)
print("Common values:", common)

Common values: [2 4 5 6 7 8 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
# False 앞에껀 nan 뒤에껀 아님

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [ ]:
Z = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]') #종료 날짜 주의

print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [ ]:
result = np.empty_like(A)
tmp = np.empty_like(A)
np.add(A, B, out=tmp)
np.divide(A, 2, out=result)
np.negative(result, out=result)
np.multiply(tmp, result, out=result)

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [ ]:
array=np.random.uniform(0,10,10)
print(array)
array1=array-(array%1)
print(array1)
print(array//1)

[8.66371876 0.32348272 1.05162769 7.90694681 0.25863571 6.49634791
 5.00848666 5.79665611 3.94690428 5.81133846]
[8. 0. 1. 7. 0. 6. 5. 5. 3. 5.]
[8. 0. 1. 7. 0. 6. 5. 5. 3. 5.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
array=np.zeros((5,5))
array+=np.arange(5)
print(array) #이거 랜덤 배치해야하는듯

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array=np.random.random(10)
array.sort()
print(array)

[0.0736842  0.55963274 0.58232666 0.62312649 0.6476664  0.8242285
 0.92959334 0.94727307 0.97048339 0.9773648 ]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal=np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [ ]:
cartesian = np.random.rand(10, 2)
print("Cartesian coordinates:\n", cartesian)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)         # 거리
theta = np.arctan2(y, x)         # 각도 (라디안)

polar = np.column_stack((r, theta))
print("\nPolar coordinates (r, theta):\n", polar)

Cartesian coordinates:
 [[0.70787718 0.69630648]
 [0.39828009 0.33112133]
 [0.34783234 0.1261323 ]
 [0.44482612 0.51692741]
 [0.99192433 0.15225507]
 [0.35633974 0.66009492]
 [0.36310903 0.5127752 ]
 [0.69862416 0.40702164]
 [0.56482533 0.26540493]
 [0.95354727 0.65773104]]

Polar coordinates (r, theta):
 [[0.9929415  0.77715819]
 [0.51794629 0.69358323]
 [0.36999553 0.34787644]
 [0.68197084 0.86022675]
 [1.00354147 0.15230593]
 [0.75013553 1.07579388]
 [0.62832044 0.95463802]
 [0.80854334 0.52753055]
 [0.62407325 0.43926956]
 [1.1583879  0.60382909]]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [ ]:
array=np.random.random(10)
print(array)
array[array.argmax()]=0
print(array)

[0.12284415 0.92615237 0.19418167 0.82273999 0.76249229 0.49564911
 0.53066689 0.45578833 0.75379764 0.49955525]
[0.12284415 0.         0.19418167 0.82273999 0.76249229 0.49564911
 0.53066689 0.45578833 0.75379764 0.49955525]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
distances=np.abs(Z-v)
closest_index=distances.argmin()
print(Z[closest_index])

96


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [ ]:
Z = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [ ]:
n = 5
p = 5
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),7)
print(Z)

[[0. 0. 0. 0. 7.]
 [7. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 7.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 3
Z = np.random.randint(0,10,(3,3))
n = 2
sorted_indices = Z[:, n].argsort()
Z_sorted = Z[sorted_indices]
print("\nArray sorted by column", n, ":\n", Z_sorted)


Array sorted by column 2 :
 [[1 8 0]
 [2 2 3]
 [2 6 9]]


In [ ]:
# column 2
Z = np.random.randint(0,10,(3,3))
n = 1
sorted_indices = Z[:, n].argsort()
Z_sorted = Z[sorted_indices]
print("\nArray sorted by column", n, ":\n", Z_sorted)


Array sorted by column 1 :
 [[2 0 2]
 [6 6 6]
 [2 9 1]]
